/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}

import java.util.ArrayList; // Importa a classe
import java.util.Arrays;
import java.util.Random;
 
public class Main {
  
  public static int direcao(){
    Random indice = new Random();
    return indice.nextInt(2);
  }
  
  public static int[] posicao() {
    Random indice = new Random();
    return new int[] {indice.nextInt(10), indice.nextInt(10)};
  } 

  public static void printar_tabuleiro(char tabuleiro[][]) {
      for(int i = 0; i < 10; i++){
        for(int j = 0; j < 10; j++)
          System.out.print(tabuleiro[i][j] + " ");
        System.out.print("\n");  
      }
  }
  
  public static void main(String[] args) {
    char[][] tabuleiro = new char[10][10];
    ArrayList<Character> navio = new ArrayList<>(Arrays.asList('P', 'E', 'C', 'S', 'N'));
 
    for(int i = 0; i < 10; i++){
      for(int j = 0; j < 10; j++)
          tabuleiro[i][j] = '.';
    }
    
    printar_tabuleiro(tabuleiro);  
       
    Random indice = new Random();
    int indice_sorteado = indice.nextInt(5);
 
  }
}
