/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.io.File;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        File arquivo = new File("/home/felipe/lista-1-FelipeABruschi/exercicio-4/tabuleiro.txt");
        char[][] tabuleiro = new char[10][10];
        Scanner entrada = new Scanner(System.in);

        System.out.println(entrada.nextLine());

        int linha = 0, coluna = 0;

        // Enquanto houver nova linha
        while(entrada.hasNext()){
            String casa = entrada.nextLine();
            System.out.println(casa.toUpperCase());
            coluna++;
        }

    }
}
