/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.lang.Math;

    public class App {

        public static void main(String[] args) {

            if (args.length < 3) {
                System.out.println("Digite pelo menos 3 cores válidas para resistores.");
                return;
            }
            Double[] tolerancia = new Double[] {0.0, 1.0, 2.0, -1.0, -1.0, 0.5, 0.25, 0.1, 0.05, 5.0, 10.0, 20.0};
            String[] resistor = new String[4];

            for (int i = 0; i < args.length; i++) {
                resistor[i] = switch (args[i]) {
                    case "preto" -> "0";
                    case "marrom" -> "1";
                    case "vermelho" -> "2";
                    case "laranja" -> "3";
                    case "amarelo" -> "4";
                    case "verde" -> "5";
                    case "azul" -> "6";
                    case "violeta" -> "7";
                    case "cinza" -> "8";
                    case "branco" -> "9";
                    case "ouro" -> "-1";
                    case "prata" -> "-2";
                    default -> "Digite um numero valido de 0 a 9";
                };
            }
            String valor_char = resistor[0] + resistor[1];
            int valor = Integer.parseInt(valor_char);

            int potencia = Integer.parseInt(resistor[2]);

            double valor_final = valor * Math.pow(10, potencia);

            System.out.printf("Resistência: %f Ohms (+- %.2f)\n", valor_final, tolerancia[3]);
        }
    }
