/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

    public class App {
        public String getGreeting() {
            return "Hello World!";
        }

        public static void main(String[] args) {
            System.out.println(new App().getGreeting());

            if (args.length < 3) {
                System.out.println("Digite pelo menos 3 cores válidas para resistores.");
                return;
            }

            String[] resistor = new String[4];

            for (int i = 0; i < args.length; i++) {
                resistor[i] = switch (args[i]) {
                    case "preto" -> "0";
                    case "marrom" -> "1";
                    case "vermelho" -> "2";
                    case "laranja" -> "3";
                    case "amarelo" -> "4";
                    case "verde" -> "5";
                    case "azul" -> "6";
                    case "violeta" -> "7";
                    case "cinza" -> "8";
                    case "branco" -> "9";
                    default -> "Digite um numero valido de 0 a 9";
                };
            }
            String valor_char = resistor[0] + resistor[1];
            int valor = Integer.parseInt(valor_char);
            System.out.println(valor);
        }
    }
