/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.lang.Math;

    public class App {

        public static void main(String[] args) {

            if (args.length < 3) {
                System.out.println("Digite pelo menos 3 cores válidas para resistores.");
                return;
            }
            Double[] tolerancia = new Double[] {0.0, 1.0, 2.0, -1.0, -1.0, 0.5, 0.25, 0.1, 0.05, 5.0, 10.0, 20.0};
            String[] resistor = new String[4];

            for (int i = 0; i < args.length; i++) {
                resistor[i] = switch (args[i]) {
                    case "preto" -> "0";
                    case "marrom" -> "1";
                    case "vermelho" -> "2";
                    case "laranja" -> "3";
                    case "amarelo" -> "4";
                    case "verde" -> "5";
                    case "azul" -> "6";
                    case "violeta" -> "7";
                    case "cinza" -> "8";
                    case "branco" -> "9";
                    case "ouro" -> "-1";
                    case "prata" -> "-2";
                    default -> "x";
                };
            }
            //validando se as cores existem para resistores
            for(int i = 0; i < args.length; i++)
                if(resistor[i].equals("x")) {
                    System.out.println("Digite pelo menos 3 cores validas.");
                    return;
                }

            //concatenando a casa1 e casa2 e transformando em int
            String valor_char = resistor[0] + resistor[1];
            int valor = Integer.parseInt(valor_char);

            int potencia = Integer.parseInt(resistor[2]);

            double valor_final = valor * Math.pow(10, potencia);
            //simplificando o resultado do valor final
            int simplifica = 0;
            while(valor_final >= 100) {
                valor_final /= 1000;
                simplifica++;
            }
            char[] siglas = new char[] {' ', 'K', 'M', 'G'};

            //verificando tolerancia
            if(args.length == 4) {
                int indice_tolerancia = Integer.parseInt(resistor[3]);
                if(indice_tolerancia == -1)
                    indice_tolerancia = 9;
                else if (indice_tolerancia == -2)
                    indice_tolerancia = 10;

                if(resistor[3].equals("4") || resistor[3].equals("3"))
                    System.out.printf("Resistência: %.2f %c Ohms\n", valor_final, siglas[simplifica]);
                else
                    System.out.printf("Resistência: %.2f %c Ohms (+- %.2f %%)\n", valor_final, siglas[simplifica], tolerancia[indice_tolerancia]);
            }
            else
                System.out.printf("Resistência: %.2f %c Ohms\n", valor_final, siglas[simplifica]);
        }
    }
